In [3]:
from euroleague_api.shot_data import ShotData

season = 2026
game_code = 1
competition_code = "E"

shotdata = ShotData(competition_code)
df = shotdata.get_game_shot_data(season, game_code)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
df.head()

,Season,Gamecode,NUM_ANOT,TEAM,ID_PLAYER,PLAYER,ID_ACTION,ACTION,POINTS,COORD_X,COORD_Y,ZONE,FASTBREAK,SECOND_CHANCE,POINTS_OFF_TURNOVER,MINUTE,CONSOLE,POINTS_A,POINTS_B,UTC
0,2026,1,7,ZAL,P000898,"VALANCIUNAS, JONAS",2FGA,Missed Two Pointer,0,62,238,E,0,0,0,1,09:43,0,0,20260924180030
1,2026,1,9,RED,P010568,"JONES, CHRIS",2FGM,Two Pointer,2,357,25,E,0,0,0,1,09:27,2,0,20260924180047
2,2026,1,11,ZAL,P011987,"EDWARDS, CARSEN",3FGM,Three Pointer,3,526,652,I,0,0,0,1,09:05,2,3,20260924180108
3,2026,1,14,RED,P010568,"JONES, CHRIS",2FGM,Two Pointer,2,-100,476,F,0,0,0,2,08:53,4,3,20260924180120
4,2026,1,15,ZAL,P011987,"EDWARDS, CARSEN",2FGA,Missed Two Pointer,0,-282,75,D,0,0,0,2,08:38,4,3,20260924180150

In [6]:
from euroleague_api.player_stats import PlayerStats

# Definisci la competizione (EuroLeague)
competition = "E" 

# Crea l'istanza dell'oggetto che definisce la variabile 'player_api'
player_api = PlayerStats(competition)

In [7]:
# Mostra tutti i metodi disponibili nella classe PlayerStats
print(dir(player_api))

# Una volta individuato il metodo (es. get_player_stats), 
# stampa la docstring dettagliata per capire quali argomenti passare
# help(player_api.get_player_stats)

['BASE_URL', 'V1', 'V2', 'V3', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'competition', 'get_gamecodes_round', 'get_gamecodes_season', 'get_player_stats', 'get_player_stats_all_seasons', 'get_player_stats_leaders', 'get_player_stats_leaders_all_seasons', 'get_player_stats_leaders_range_seasons', 'get_player_stats_leaders_single_season', 'get_player_stats_range_seasons', 'get_player_stats_single_season', 'get_range_seasons_data', 'get_round_data_from_game_data', 'get_season_data_from_game_data', 'make_season_game_url', 'url', 'url_v1', 'url_v2']

In [8]:
help(player_api.get_player_stats_single_season)

Help on method get_player_stats_single_season in module euroleague_api.player_stats:

get_player_stats_single_season(endpoint: str, season: int, phase_type_code: Optional[str] = None, statistic_mode: str = 'PerGame') -> pandas.core.frame.DataFrame method of euroleague_api.player_stats.PlayerStats instance
    The players' stats for a *single* season.

    Args:

        endpoint (str): The type of stats, available variables:
            - traditional
            - advanced
            - misc
            - scoring

        season (int): The start year of the season.

        phase_type_code (Optional[str], optional): The phase of the season,
            available variables:
            - "RS" (regular season)
            - "PO" (play-off)
            - "FF" (final four)
            Defaults to None, which includes all phases.

        statistic_mode (str, optional): The aggregation of statistics,
            available variables:
             - PerGame
             - Accumulated
             - PerMinute
             - Per100Possesions
             - PerGameReverse
             - AccumulatedReverse
            Defaults to "PerGame".

    Returns:

        pd.DataFrame: A dataframe with the players' stats

In [9]:
import pandas as pd
import numpy as np

In [21]:
player_api = PlayerStats('E')

df_leaders = player_api.get_player_stats_leaders_single_season(
    season=2026,
    stat_category = 'Score',
    statistic_mode = 'PerGame'
)
df_leaders.head()

,rank,playerCode,playerName,playerAbbreviatedName,imageUrl,teamImageUrl,timePlayed,averageTimePlayed,secondsPlayed,gamesPlayed,possessions,total,averagePerGame,averagePerMinute,averagePer100Possessions,clubCodes,clubNames,abbreviatedClubNames,tvCodes,clubSeasonCodes
0,1,012640,"HIFI, NADIR",,https://media-cdn.cortextech.io/1dU3kpCqReRp93...,https://media-cdn.incrowdsports.com/a033e5b3-0...,104:17,26:04,6257,4,107.88,81.0,20.250000,31.069202,75.083426,PRS,Paris Basketball,Paris,PBB,E2026
1,2,003469,"VEZENKOV, SASHA","Vezenkov, A.",https://media-cdn.cortextech.io/1dU3kpCqReRp93...,https://media-cdn.incrowdsports.com/789423ac-3...,149:51,24:58,8991,6,82.64,108.0,18.000000,28.828829,130.687318,OLY,Olympiacos Piraeus,Olympiacos,OLY,E2026
2,3,011286,"BACON, DWAYNE","Bacon, D.",https://media-cdn.cortextech.io/1dU3kpCqReRp93...,https://media-cdn.incrowdsports.com/1efae090-1...,162:28,27:05,9748,6,106.52,107.0,17.833333,26.343865,100.450620,DUB,Dubai Basketball,Dubai,DUB,E2026
3,4,011987,"EDWARDS, CARSEN",,https://media-cdn.cortextech.io/1dU3kpCqReRp93...,https://media-cdn.incrowdsports.com/0aa09358-3...,143:21,23:54,8601,6,124.04,103.0,17.166667,28.740844,83.037730,ZAL,Zalgiris Kaunas,Zalgiris,ZAL,E2026
4,5,006661,"WILBEKIN, SCOTTIE","Wilbekin, S.",https://media-cdn.cortextech.io/1dU3kpCqReRp93...,https://media-cdn.cortextech.io/1dU3kpCqReRp93...,143:29,23:55,8609,6,111.48,102.0,17.000000,28.435358,91.496233,BES,Besiktas Istanbul,Besiktas,BJK,E2026

In [18]:
import inspect
from euroleague_api.player_stats import PlayerStats

player_api = PlayerStats("E")

# Estraiamo la "firma" esatta (la lista degli argomenti accettati)
firma = inspect.signature(player_api.get_player_stats_leaders_single_season)
print("I parametri corretti sono:")
print(firma)

# Stampiamo anche la docstring per vedere se l'autore ha lasciato indicazioni
print("\nDocumentazione della funzione:")
print(player_api.get_player_stats_leaders_single_season.__doc__)

I parametri corretti sono:
(season: int, club_code: Optional[str] = None, round_number: Optional[int] = None, max_round: Optional[int] = None, stat_category: str | None = None, top_n: int = 200, phase_type_code: Optional[str] = None, statistic_mode: str = 'PerGame', game_type: Optional[str] = None, position: Optional[str] = None) -> pandas.core.frame.DataFrame

Documentazione della funzione:

        Get the top leaders in a statistical category in a single season

        Args:

            season (int): The start year of the season.

            club_code (Optional[str], optional): The code of the club to
                draw the top stats from. Defaults to None, meaning all clubs.

            round_number (Optional[int], optional): The round number to draw
                the top stats from. Defaults to None, meaning all rounds.

            max_round (Optional[int], optional): The maximum round number to
                draw the top stats from. Defaults to None, meaning all rounds.

            stat_category (str): The stat category. See function
                `self.get_player_stats_leaders` for a list of available stats.

            top_n (int): The number of top N players to return.
                Defaults to 200.

            phase_type_code (Optional[str], optional): The phase of the season,
                available variables:
                - "RS" (regular season)
                - "PO" (play-off)
                - "FF" (final four)
                Defaults to None, which includes all phases.

            statistic_mode (str, optional): The aggregation of statistics,
                available variables:
                - PerGame
                - Accumulated
                - PerMinute
                - Per100Possesions
                - PerGameReverse
                - AccumulatedReverse
                Defaults to "PerGame".

            game_type (Optional[str], optional): The type of games to draw the
                top stats from. Available values:
                - HomeGames
                - AwayGames
                - GamesWon
                - GamesLost
                Defaults to None, meaning all games

            position (Optional[str], optional): The position of the player to
                draw the top stats from. Available values:
                - Guards
                - Forwards
                - Centers
                - RisingStars
                Defaults to None, meaning all positions.

        Returns:

            pd.DataFrame: A dataframe with the top leading players and their
                stat